// ============================================================
// Plantarea Mock Data
// Seed data that mirrors the backend — used for static/GitHub Pages deployment
// ============================================================

import type { Category, Nursery, Product, Review, Order } from "@/types";

// --- Categories ---
export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name: "Árboles nativos", slug: "arboles-nativos", description: "Especies arbóreas nativas de Chile, ideales para reforestar y embellecer jardines con flora autóctona.", icon: "🌳", product_count: 5 },
  { id: 2, name: "Árboles frutales", slug: "arboles-frutales", description: "Árboles que producen frutas deliciosas para tu huerto o jardín.", icon: "🍎", product_count: 5 },
  { id: 3, name: "Plantas de interior", slug: "plantas-interior", description: "Plantas perfectas para embellecer espacios interiores con poca luz.", icon: "🪴", product_count: 5 },
  { id: 4, name: "Flores y bulbos", slug: "flores-bulbos", description: "Flores llamativas y bulbos para llenar de color tus espacios.", icon: "🌸", product_count: 4 },
  { id: 5, name: "Cactus y suculentas", slug: "cactus-suculentas", description: "Plantas resistentes y de bajo mantenimiento, perfectas para climas áridos.", icon: "🌵", product_count: 5 },
  { id: 6, name: "Hierbas aromáticas", slug: "hierbas-aromaticas", description: "Hierbas culinarias y medicinales para tu huerto en casa.", icon: "🌿", product_count: 5 },
  { id: 7, name: "Arbustos y setos", slug: "arbustos-setos", description: "Arbustos y plantas para setos vivos, privacidad y estructura en jardines.", icon: "🌲", product_count: 0 },
  { id: 8, name: "Trepadoras", slug: "trepadoras", description: "Plantas trepadoras para cubrir muros, pérgolas y estructuras.", icon: "🍃", product_count: 0 },
];

// --- Nurseries ---
export const MOCK_NURSERIES: Nursery[] = [
  {
    id: 1,
    name: "Vivero Los Aromos",
    slug: "vivero-los-aromos",
    description: "Especialistas en flora nativa chilena con más de 20 años de experiencia. Promovemos la biodiversidad y la reforestación con especies autóctonas.",
    address: "Camino Los Aromos 1250",
    city: "Limache",
    region: "Valparaíso",
    phone: "+56 9 8123 4567",
    email: "contacto@losароmos.cl",
    logo_url: "https://picsum.photos/seed/aromos-logo/200/200",
    cover_url: "https://picsum.photos/seed/vivero-los-aromos/1200/400",
    rating: 4.8,
    review_count: 42,
    is_active: true,
    created_at: "2026-01-05T10:00:00Z",
  },
  {
    id: 2,
    name: "Vivero Santa Elena",
    slug: "vivero-santa-elena",
    description: "Tu fuente de árboles frutales de calidad en la Región Metropolitana. Contamos con variedades adaptadas al clima de Chile central.",
    address: "Av. Santa Elena 3400",
    city: "Santiago",
    region: "Región Metropolitana",
    phone: "+56 9 7234 5678",
    email: "ventas@santaelena.cl",
    logo_url: "https://picsum.photos/seed/santa-elena-logo/200/200",
    cover_url: "https://picsum.photos/seed/vivero-santa-elena/1200/400",
    rating: 4.5,
    review_count: 38,
    is_active: true,
    created_at: "2026-01-10T09:00:00Z",
  },
  {
    id: 3,
    name: "Jardines del Sur",
    slug: "jardines-del-sur",
    description: "Plantas de interior y arbustos ornamentales del corazón de la Araucanía. Expertos en especies adaptadas al clima del sur de Chile.",
    address: "Ruta 5 Sur km 677",
    city: "Temuco",
    region: "Araucanía",
    phone: "+56 9 6345 6789",
    email: "info@jardinesdelSur.cl",
    logo_url: "https://picsum.photos/seed/jardines-sur-logo/200/200",
    cover_url: "https://picsum.photos/seed/jardines-del-sur/1200/400",
    rating: 4.6,
    review_count: 27,
    is_active: true,
    created_at: "2026-01-15T11:00:00Z",
  },
  {
    id: 4,
    name: "Cactus Chile",
    slug: "cactus-chile",
    description: "El mayor vivero de cactáceas y suculentas de Chile. Más de 500 especies en stock, desde cactus desérticos chilenos hasta suculentas de colección.",
    address: "Av. Francisco de Aguirre 1890",
    city: "La Serena",
    region: "Coquimbo",
    phone: "+56 9 5456 7890",
    email: "hola@cactuschile.cl",
    logo_url: "https://picsum.photos/seed/cactus-chile-logo/200/200",
    cover_url: "https://picsum.photos/seed/cactus-chile/1200/400",
    rating: 4.9,
    review_count: 56,
    is_active: true,
    created_at: "2026-01-20T08:00:00Z",
  },
  {
    id: 5,
    name: "Vivero El Boldo",
    slug: "vivero-el-boldo",
    description: "Hierbas aromáticas y medicinales cultivadas de manera orgánica en Casablanca. Todos nuestros productos son libres de pesticidas.",
    address: "Parcela 12, Fundo El Boldo",
    city: "Casablanca",
    region: "Valparaíso",
    phone: "+56 9 4567 8901",
    email: "organico@elboldo.cl",
    logo_url: "https://picsum.photos/seed/el-boldo-logo/200/200",
    cover_url: "https://picsum.photos/seed/vivero-el-boldo/1200/400",
    rating: 4.7,
    review_count: 19,
    is_active: true,
    created_at: "2026-01-25T14:00:00Z",
  },
  {
    id: 6,
    name: "Flora Valdiviana",
    slug: "flora-valdiviana",
    description: "Especialistas en la flora del bosque templado valdiviano. Cultivamos especies endémicas de la zona, contribuyendo a la conservación de este ecosistema único.",
    address: "Camino Corral km 8",
    city: "Valdivia",
    region: "Los Ríos",
    phone: "+56 9 3678 9012",
    email: "contacto@floravaldiviana.cl",
    logo_url: "https://picsum.photos/seed/flora-valdiviana-logo/200/200",
    cover_url: "https://picsum.photos/seed/flora-valdiviana/1200/400",
    rating: 4.4,
    review_count: 15,
    is_active: true,
    created_at: "2026-02-01T10:00:00Z",
  },
];

// Helper references for nested objects
const CAT = Object.fromEntries(MOCK_CATEGORIES.map((c) => [c.id, c]));
const NUR = Object.fromEntries(MOCK_NURSERIES.map((n) => [n.id, n]));

// --- Products ---
export const MOCK_PRODUCTS: Product[] = [
  // === Árboles nativos (category 1) — Vivero Los Aromos (nursery 1) ===
  {
    id: 1,
    name: "Araucaria",
    slug: "araucaria",
    description: "La Araucaria araucana, símbolo de Chile, es un árbol milenario de gran porte. Crecimiento lento pero majestuoso, ideal para espacios amplios.",
    price: 25000,
    compare_at_price: 30000,
    stock: 12,
    sku: "ARO-NAT-001",
    image_url: "https://picsum.photos/seed/araucaria/400/400",
    images: ["https://picsum.photos/seed/araucaria/400/400", "https://picsum.photos/seed/araucaria-2/400/400"],
    category_id: 1,
    nursery_id: 1,
    is_active: true,
    created_at: "2026-01-06T10:00:00Z",
    category: CAT[1],
    nursery: NUR[1],
  },
  {
    id: 2,
    name: "Boldo",
    slug: "boldo",
    description: "El Boldo (Peumus boldus) es un árbol nativo de Chile con propiedades medicinales reconocidas. Aromático y resistente a la sequía.",
    price: 8500,
    compare_at_price: null,
    stock: 25,
    sku: "ARO-NAT-002",
    image_url: "https://picsum.photos/seed/boldo/400/400",
    images: ["https://picsum.photos/seed/boldo/400/400"],
    category_id: 1,
    nursery_id: 1,
    is_active: true,
    created_at: "2026-01-06T11:00:00Z",
    category: CAT[1],
    nursery: NUR[1],
  },
  {
    id: 3,
    name: "Quillay",
    slug: "quillay",
    description: "El Quillay (Quillaja saponaria) es un árbol nativo chileno de gran valor ecológico y medicinal. Su corteza contiene saponinas naturales.",
    price: 7500,
    compare_at_price: null,
    stock: 18,
    sku: "ARO-NAT-003",
    image_url: "https://picsum.photos/seed/quillay/400/400",
    images: ["https://picsum.photos/seed/quillay/400/400"],
    category_id: 1,
    nursery_id: 1,
    is_active: true,
    created_at: "2026-01-07T09:00:00Z",
    category: CAT[1],
    nursery: NUR[1],
  },
  {
    id: 4,
    name: "Canelo",
    slug: "canelo",
    description: "El Canelo (Drimys winteri) es el árbol sagrado del pueblo mapuche. Florece en invierno con hermosas flores blancas.",
    price: 9000,
    compare_at_price: null,
    stock: 15,
    sku: "ARO-NAT-004",
    image_url: "https://picsum.photos/seed/canelo/400/400",
    images: ["https://picsum.photos/seed/canelo/400/400"],
    category_id: 1,
    nursery_id: 1,
    is_active: true,
    created_at: "2026-01-07T10:00:00Z",
    category: CAT[1],
    nursery: NUR[1],
  },
  {
    id: 5,
    name: "Peumo",
    slug: "peumo",
    description: "El Peumo (Cryptocarya alba) es un árbol nativo siempreverde, muy común en el bosque esclerófilo de Chile central.",
    price: 8000,
    compare_at_price: null,
    stock: 20,
    sku: "ARO-NAT-005",
    image_url: "https://picsum.photos/seed/peumo/400/400",
    images: ["https://picsum.photos/seed/peumo/400/400"],
    category_id: 1,
    nursery_id: 1,
    is_active: true,
    created_at: "2026-01-08T09:00:00Z",
    category: CAT[1],
    nursery: NUR[1],
  },

  // === Árboles frutales (category 2) — Vivero Santa Elena (nursery 2) ===
  {
    id: 6,
    name: "Limonero",
    slug: "limonero",
    description: "Limonero (Citrus limon) variedad Eureka, producción de limones todo el año. Ideal para jardines y macetones grandes.",
    price: 15000,
    compare_at_price: 18000,
    stock: 30,
    sku: "STE-FRU-001",
    image_url: "https://picsum.photos/seed/limonero/400/400",
    images: ["https://picsum.photos/seed/limonero/400/400", "https://picsum.photos/seed/limonero-2/400/400"],
    category_id: 2,
    nursery_id: 2,
    is_active: true,
    created_at: "2026-01-11T09:00:00Z",
    category: CAT[2],
    nursery: NUR[2],
  },
  {
    id: 7,
    name: "Naranjo",
    slug: "naranjo",
    description: "Naranjo (Citrus sinensis) variedad Washington Navel, fruta dulce y sin semillas. Producción abundante en primavera.",
    price: 14000,
    compare_at_price: null,
    stock: 22,
    sku: "STE-FRU-002",
    image_url: "https://picsum.photos/seed/naranjo/400/400",
    images: ["https://picsum.photos/seed/naranjo/400/400"],
    category_id: 2,
    nursery_id: 2,
    is_active: true,
    created_at: "2026-01-11T10:00:00Z",
    category: CAT[2],
    nursery: NUR[2],
  },
  {
    id: 8,
    name: "Palto Hass",
    slug: "palto-hass",
    description: "Palta Hass (Persea americana), la variedad más consumida en Chile. Produce frutos de excelente calidad con piel rugosa y oscura.",
    price: 18000,
    compare_at_price: 22000,
    stock: 15,
    sku: "STE-FRU-003",
    image_url: "https://picsum.photos/seed/palto-hass/400/400",
    images: ["https://picsum.photos/seed/palto-hass/400/400"],
    category_id: 2,
    nursery_id: 2,
    is_active: true,
    created_at: "2026-01-12T09:00:00Z",
    category: CAT[2],
    nursery: NUR[2],
  },
  {
    id: 9,
    name: "Cerezo",
    slug: "cerezo",
    description: "Cerezo (Prunus avium) variedad Bing, produce cerezas grandes y dulces. Espectacular floración blanca en primavera.",
    price: 16000,
    compare_at_price: null,
    stock: 10,
    sku: "STE-FRU-004",
    image_url: "https://picsum.photos/seed/cerezo/400/400",
    images: ["https://picsum.photos/seed/cerezo/400/400"],
    category_id: 2,
    nursery_id: 2,
    is_active: true,
    created_at: "2026-01-12T10:00:00Z",
    category: CAT[2],
    nursery: NUR[2],
  },
  {
    id: 10,
    name: "Higuera",
    slug: "higuera",
    description: "Higuera (Ficus carica) variedad Brown Turkey. Produce higos dulces en verano y otoño. Muy rústica y fácil de cuidar.",
    price: 12000,
    compare_at_price: null,
    stock: 18,
    sku: "STE-FRU-005",
    image_url: "https://picsum.photos/seed/higuera/400/400",
    images: ["https://picsum.photos/seed/higuera/400/400"],
    category_id: 2,
    nursery_id: 2,
    is_active: true,
    created_at: "2026-01-13T09:00:00Z",
    category: CAT[2],
    nursery: NUR[2],
  },

  // === Plantas de interior (category 3) — Jardines del Sur (nursery 3) ===
  {
    id: 11,
    name: "Monstera",
    slug: "monstera",
    description: "La Monstera deliciosa, con sus icónicas hojas perforadas, es la reina de las plantas de interior. Crece bien con luz indirecta.",
    price: 12000,
    compare_at_price: null,
    stock: 20,
    sku: "JDS-INT-001",
    image_url: "https://picsum.photos/seed/monstera/400/400",
    images: ["https://picsum.photos/seed/monstera/400/400"],
    category_id: 3,
    nursery_id: 3,
    is_active: true,
    created_at: "2026-01-16T09:00:00Z",
    category: CAT[3],
    nursery: NUR[3],
  },
  {
    id: 12,
    name: "Ficus lyrata",
    slug: "ficus-lyrata",
    description: "El Ficus lyrata o Ficus pandurata es una de las plantas de interior más elegantes. Sus grandes hojas en forma de violín son inconfundibles.",
    price: 18000,
    compare_at_price: null,
    stock: 8,
    sku: "JDS-INT-002",
    image_url: "https://picsum.photos/seed/ficus-lyrata/400/400",
    images: ["https://picsum.photos/seed/ficus-lyrata/400/400"],
    category_id: 3,
    nursery_id: 3,
    is_active: true,
    created_at: "2026-01-16T10:00:00Z",
    category: CAT[3],
    nursery: NUR[3],
  },
  {
    id: 13,
    name: "Pothos",
    slug: "pothos",
    description: "El Pothos (Epipremnum aureum) es la planta de interior perfecta para principiantes. Purifica el aire y crece en casi cualquier condición.",
    price: 5500,
    compare_at_price: null,
    stock: 40,
    sku: "JDS-INT-003",
    image_url: "https://picsum.photos/seed/pothos/400/400",
    images: ["https://picsum.photos/seed/pothos/400/400"],
    category_id: 3,
    nursery_id: 3,
    is_active: true,
    created_at: "2026-01-17T09:00:00Z",
    category: CAT[3],
    nursery: NUR[3],
  },
  {
    id: 14,
    name: "Copihue",
    slug: "copihue",
    description: "El Copihue (Lapageria rosea), flor nacional de Chile. Trepadora de interior con impresionantes flores acampanadas rojas o blancas.",
    price: 15000,
    compare_at_price: 19000,
    stock: 6,
    sku: "JDS-INT-004",
    image_url: "https://picsum.photos/seed/copihue/400/400",
    images: ["https://picsum.photos/seed/copihue/400/400", "https://picsum.photos/seed/copihue-2/400/400"],
    category_id: 3,
    nursery_id: 3,
    is_active: true,
    created_at: "2026-01-17T10:00:00Z",
    category: CAT[3],
    nursery: NUR[3],
  },
  {
    id: 15,
    name: "Azalea",
    slug: "azalea",
    description: "Azalea (Rhododendron simsii), arbusto de interior con abundante floración en tonos rosas, rojos y blancos. Perfecta para interiores frescos.",
    price: 9500,
    compare_at_price: null,
    stock: 14,
    sku: "JDS-INT-005",
    image_url: "https://picsum.photos/seed/azalea/400/400",
    images: ["https://picsum.photos/seed/azalea/400/400"],
    category_id: 3,
    nursery_id: 3,
    is_active: true,
    created_at: "2026-01-18T09:00:00Z",
    category: CAT[3],
    nursery: NUR[3],
  },

  // === Cactus y suculentas (category 5) — Cactus Chile (nursery 4) ===
  {
    id: 16,
    name: "Echinopsis",
    slug: "echinopsis",
    description: "Echinopsis atacamensis, cactus columnar del desierto atacameño. Produce enormes flores blancas que duran solo una noche.",
    price: 6000,
    compare_at_price: null,
    stock: 30,
    sku: "CCH-CAC-001",
    image_url: "https://picsum.photos/seed/echinopsis/400/400",
    images: ["https://picsum.photos/seed/echinopsis/400/400"],
    category_id: 5,
    nursery_id: 4,
    is_active: true,
    created_at: "2026-01-21T09:00:00Z",
    category: CAT[5],
    nursery: NUR[4],
  },
  {
    id: 17,
    name: "Copiapoa",
    slug: "copiapoa",
    description: "Copiapoa cinerea, cactus endémico del desierto de Atacama. Una de las plantas más raras y codiciadas por coleccionistas.",
    price: 12000,
    compare_at_price: null,
    stock: 8,
    sku: "CCH-CAC-002",
    image_url: "https://picsum.photos/seed/copiapoa/400/400",
    images: ["https://picsum.photos/seed/copiapoa/400/400"],
    category_id: 5,
    nursery_id: 4,
    is_active: true,
    created_at: "2026-01-21T10:00:00Z",
    category: CAT[5],
    nursery: NUR[4],
  },
  {
    id: 18,
    name: "Echeveria",
    slug: "echeveria",
    description: "Echeveria elegans, suculenta de roseta perfecta con hojas azuladas. Ideal para maceteros, terrarios y arreglos de suculentas.",
    price: 3500,
    compare_at_price: null,
    stock: 60,
    sku: "CCH-CAC-003",
    image_url: "https://picsum.photos/seed/echeveria/400/400",
    images: ["https://picsum.photos/seed/echeveria/400/400"],
    category_id: 5,
    nursery_id: 4,
    is_active: true,
    created_at: "2026-01-22T09:00:00Z",
    category: CAT[5],
    nursery: NUR[4],
  },
  {
    id: 19,
    name: "Pack suculentas",
    slug: "pack-suculentas",
    description: "Pack de 6 suculentas variadas seleccionadas por nuestros expertos. Incluye guía de cuidados y sustrato especial.",
    price: 15000,
    compare_at_price: 21000,
    stock: 20,
    sku: "CCH-CAC-004",
    image_url: "https://picsum.photos/seed/pack-suculentas/400/400",
    images: ["https://picsum.photos/seed/pack-suculentas/400/400"],
    category_id: 5,
    nursery_id: 4,
    is_active: true,
    created_at: "2026-01-22T10:00:00Z",
    category: CAT[5],
    nursery: NUR[4],
  },
  {
    id: 20,
    name: "Aloe vera",
    slug: "aloe-vera",
    description: "Aloe vera, la planta medicinal por excelencia. Su gel tiene propiedades cicatrizantes, hidratantes y antiinflamatorias.",
    price: 8000,
    compare_at_price: null,
    stock: 35,
    sku: "CCH-CAC-005",
    image_url: "https://picsum.photos/seed/aloe-vera/400/400",
    images: ["https://picsum.photos/seed/aloe-vera/400/400"],
    category_id: 5,
    nursery_id: 4,
    is_active: true,
    created_at: "2026-01-23T09:00:00Z",
    category: CAT[5],
    nursery: NUR[4],
  },

  // === Hierbas aromáticas (category 6) — Vivero El Boldo (nursery 5) ===
  {
    id: 21,
    name: "Albahaca",
    slug: "albahaca",
    description: "Albahaca genovesa orgánica, la hierba aromática más popular de la cocina mediterránea. Cultivo sin pesticidas.",
    price: 2500,
    compare_at_price: null,
    stock: 50,
    sku: "ELB-HRB-001",
    image_url: "https://picsum.photos/seed/albahaca/400/400",
    images: ["https://picsum.photos/seed/albahaca/400/400"],
    category_id: 6,
    nursery_id: 5,
    is_active: true,
    created_at: "2026-01-26T09:00:00Z",
    category: CAT[6],
    nursery: NUR[5],
  },
  {
    id: 22,
    name: "Romero",
    slug: "romero",
    description: "Romero (Rosmarinus officinalis) orgánico. Aromático y resistente, ideal para jardines mediterráneos y uso culinario.",
    price: 3500,
    compare_at_price: null,
    stock: 40,
    sku: "ELB-HRB-002",
    image_url: "https://picsum.photos/seed/romero/400/400",
    images: ["https://picsum.photos/seed/romero/400/400"],
    category_id: 6,
    nursery_id: 5,
    is_active: true,
    created_at: "2026-01-26T10:00:00Z",
    category: CAT[6],
    nursery: NUR[5],
  },
  {
    id: 23,
    name: "Lavanda",
    slug: "lavanda",
    description: "Lavanda (Lavandula angustifolia) orgánica, con fragancia inconfundible. Atrae polinizadores y repele mosquitos naturalmente.",
    price: 4000,
    compare_at_price: null,
    stock: 35,
    sku: "ELB-HRB-003",
    image_url: "https://picsum.photos/seed/lavanda/400/400",
    images: ["https://picsum.photos/seed/lavanda/400/400"],
    category_id: 6,
    nursery_id: 5,
    is_active: true,
    created_at: "2026-01-27T09:00:00Z",
    category: CAT[6],
    nursery: NUR[5],
  },
  {
    id: 24,
    name: "Menta",
    slug: "menta",
    description: "Menta piperita orgánica. Infaltable en la cocina y para preparar aguas frescas e infusiones. Crece vigorosa en maceteros.",
    price: 2000,
    compare_at_price: null,
    stock: 55,
    sku: "ELB-HRB-004",
    image_url: "https://picsum.photos/seed/menta/400/400",
    images: ["https://picsum.photos/seed/menta/400/400"],
    category_id: 6,
    nursery_id: 5,
    is_active: true,
    created_at: "2026-01-27T10:00:00Z",
    category: CAT[6],
    nursery: NUR[5],
  },
  {
    id: 25,
    name: "Kit huerto",
    slug: "kit-huerto",
    description: "Kit completo de huerto aromático orgánico: albahaca, romero, menta, tomillo y orégano. Incluye macetero de madera reciclada.",
    price: 8500,
    compare_at_price: 10000,
    stock: 15,
    sku: "ELB-HRB-005",
    image_url: "https://picsum.photos/seed/kit-huerto/400/400",
    images: ["https://picsum.photos/seed/kit-huerto/400/400", "https://picsum.photos/seed/kit-huerto-2/400/400"],
    category_id: 6,
    nursery_id: 5,
    is_active: true,
    created_at: "2026-01-28T09:00:00Z",
    category: CAT[6],
    nursery: NUR[5],
  },

  // === Flores y bulbos (category 4) — Flora Valdiviana (nursery 6) ===
  {
    id: 26,
    name: "Fucsia",
    slug: "fucsia",
    description: "Fucsia (Fuchsia magellanica), arbusto nativo del bosque valdiviano con flores colgantes bicolores. Perfecta para jardines húmedos y sombreados.",
    price: 6500,
    compare_at_price: null,
    stock: 22,
    sku: "FLV-FLR-001",
    image_url: "https://picsum.photos/seed/fucsia/400/400",
    images: ["https://picsum.photos/seed/fucsia/400/400"],
    category_id: 4,
    nursery_id: 6,
    is_active: true,
    created_at: "2026-02-02T09:00:00Z",
    category: CAT[4],
    nursery: NUR[6],
  },
  {
    id: 27,
    name: "Helecho",
    slug: "helecho",
    description: "Helecho nativo del bosque valdiviano (Blechnum chilense). Frondoso y de rápido crecimiento, ideal para jardines sombríos y húmedos.",
    price: 7000,
    compare_at_price: null,
    stock: 18,
    sku: "FLV-FLR-002",
    image_url: "https://picsum.photos/seed/helecho/400/400",
    images: ["https://picsum.photos/seed/helecho/400/400"],
    category_id: 4,
    nursery_id: 6,
    is_active: true,
    created_at: "2026-02-02T10:00:00Z",
    category: CAT[4],
    nursery: NUR[6],
  },
  {
    id: 28,
    name: "Hortensia",
    slug: "hortensia",
    description: "Hortensia (Hydrangea macrophylla) del sur de Chile, aclimatada a lluvias y temperaturas frescas. Grandes inflorescencias azules y lilas.",
    price: 8500,
    compare_at_price: null,
    stock: 16,
    sku: "FLV-FLR-003",
    image_url: "https://picsum.photos/seed/hortensia/400/400",
    images: ["https://picsum.photos/seed/hortensia/400/400"],
    category_id: 4,
    nursery_id: 6,
    is_active: true,
    created_at: "2026-02-03T09:00:00Z",
    category: CAT[4],
    nursery: NUR[6],
  },
  {
    id: 29,
    name: "Notro",
    slug: "notro",
    description: "Notro o Ciruelillo (Embothrium coccineum), árbol nativo de impresionantes flores tubulares rojas. Espectacular en la floración de primavera.",
    price: 11000,
    compare_at_price: null,
    stock: 10,
    sku: "FLV-FLR-004",
    image_url: "https://picsum.photos/seed/notro/400/400",
    images: ["https://picsum.photos/seed/notro/400/400"],
    category_id: 4,
    nursery_id: 6,
    is_active: true,
    created_at: "2026-02-03T10:00:00Z",
    category: CAT[4],
    nursery: NUR[6],
  },
];

// --- Reviews ---
export const MOCK_REVIEWS: Review[] = [
  { id: 1, nursery_id: 1, author_name: "María González", rating: 5, comment: "Excelente vivero, las plantas llegaron en perfectas condiciones. La Araucaria que compré está creciendo increíble.", created_at: "2026-01-20T14:00:00Z" },
  { id: 2, nursery_id: 1, author_name: "Carlos Muñoz", rating: 5, comment: "Gran variedad de flora nativa, precios justos y personal muy atento. Recomendado al 100%.", created_at: "2026-01-25T10:00:00Z" },
  { id: 3, nursery_id: 1, author_name: "Lucía Fernández", rating: 4, comment: "Muy buena experiencia. El Boldo que compré está hermoso. Podría mejorar el embalaje para envíos.", created_at: "2026-02-01T11:00:00Z" },
  { id: 4, nursery_id: 2, author_name: "Andrés Pérez", rating: 5, comment: "El limonero que pedí llegó injertado y ya tiene limones. Servicio de primera calidad.", created_at: "2026-01-22T09:00:00Z" },
  { id: 5, nursery_id: 2, author_name: "Valentina Rojas", rating: 4, comment: "Buen vivero, el palto hass llegó bien embalado. Tardó un par de días más de lo esperado.", created_at: "2026-02-05T15:00:00Z" },
  { id: 6, nursery_id: 3, author_name: "Felipe Morales", rating: 5, comment: "El Copihue es simplemente espectacular. No creía encontrarlo tan saludable. Jardines del Sur es un tesoro.", created_at: "2026-01-30T12:00:00Z" },
  { id: 7, nursery_id: 3, author_name: "Camila Soto", rating: 4, comment: "Buena atención y plantas muy sanas. La Monstera está enorme. Recomendado.", created_at: "2026-02-10T10:00:00Z" },
  { id: 8, nursery_id: 4, author_name: "Diego Vargas", rating: 5, comment: "La Copiapoa que compré es una joya. Cactus Chile tiene plantas de colección que no se consiguen en otro lado.", created_at: "2026-01-28T16:00:00Z" },
  { id: 9, nursery_id: 4, author_name: "Sofía Contreras", rating: 5, comment: "El pack de suculentas llegó perfecto, cada una en su macetero individual. Una presentación impecable.", created_at: "2026-02-08T11:00:00Z" },
  { id: 10, nursery_id: 4, author_name: "Rodrigo Navarro", rating: 5, comment: "La mejor selección de cactus que he visto online. Envíos cuidadosos y rápidos desde La Serena.", created_at: "2026-02-15T14:00:00Z" },
  { id: 11, nursery_id: 5, author_name: "Isidora Lagos", rating: 5, comment: "Las hierbas aromáticas son de primera calidad. Saben que son orgánicas desde el primer momento que las hueles.", created_at: "2026-02-03T09:00:00Z" },
  { id: 12, nursery_id: 5, author_name: "Matías Herrera", rating: 4, comment: "El kit de huerto es un regalo perfecto. Muy buena presentación y las plantas llegaron sanas.", created_at: "2026-02-20T13:00:00Z" },
  { id: 13, nursery_id: 6, author_name: "Antonia Reyes", rating: 4, comment: "Hermosas plantas del bosque valdiviano. La hortensia está floreciendo enorme. Solo bajé una estrella porque el envío demoró.", created_at: "2026-02-12T10:00:00Z" },
  { id: 14, nursery_id: 6, author_name: "Benjamín Castro", rating: 5, comment: "El Notro es simplemente impresionante. Se nota que en Flora Valdiviana aman sus plantas. Volveré a comprar.", created_at: "2026-02-25T15:00:00Z" },
];

// --- Orders (sample data for admin views) ---
export const MOCK_ORDERS: Order[] = [
  {
    id: 1,
    buyer_name: "María González",
    buyer_email: "maria.gonzalez@email.com",
    buyer_phone: "+56 9 8765 4321",
    shipping_address: "Av. Los Leones 1234, Providencia, Santiago",
    status: "delivered",
    total: 33500,
    notes: null,
    nursery_id: 1,
    nursery_name: "Vivero Los Aromos",
    items: [
      { id: 1, product_id: 1, product_name: "Araucaria", product_image_url: "https://picsum.photos/seed/araucaria/400/400", quantity: 1, unit_price: 25000, subtotal: 25000 },
      { id: 2, product_id: 2, product_name: "Boldo", product_image_url: "https://picsum.photos/seed/boldo/400/400", quantity: 1, unit_price: 8500, subtotal: 8500 },
    ],
    created_at: "2026-02-10T10:00:00Z",
    updated_at: "2026-02-12T14:00:00Z",
  },
  {
    id: 2,
    buyer_name: "Andrés Pérez",
    buyer_email: "andres.perez@email.com",
    buyer_phone: "+56 9 7654 3210",
    shipping_address: "Calle Merced 456, Santiago Centro",
    status: "confirmed",
    total: 32000,
    notes: "Por favor incluir macetón de 50cm",
    nursery_id: 2,
    nursery_name: "Vivero Santa Elena",
    items: [
      { id: 3, product_id: 8, product_name: "Palto Hass", product_image_url: "https://picsum.photos/seed/palto-hass/400/400", quantity: 1, unit_price: 18000, subtotal: 18000 },
      { id: 4, product_id: 6, product_name: "Limonero", product_image_url: "https://picsum.photos/seed/limonero/400/400", quantity: 1, unit_price: 15000, subtotal: 15000 },
    ],
    created_at: "2026-03-01T11:00:00Z",
    updated_at: "2026-03-01T12:00:00Z",
  },
  {
    id: 3,
    buyer_name: "Sofía Contreras",
    buyer_email: "sofia.c@email.com",
    buyer_phone: null,
    shipping_address: "Pasaje Los Cóndores 789, Las Condes",
    status: "pending",
    total: 30500,
    notes: null,
    nursery_id: 4,
    nursery_name: "Cactus Chile",
    items: [
      { id: 5, product_id: 19, product_name: "Pack suculentas", product_image_url: "https://picsum.photos/seed/pack-suculentas/400/400", quantity: 1, unit_price: 15000, subtotal: 15000 },
      { id: 6, product_id: 17, product_name: "Copiapoa", product_image_url: "https://picsum.photos/seed/copiapoa/400/400", quantity: 1, unit_price: 12000, subtotal: 12000 },
      { id: 7, product_id: 18, product_name: "Echeveria", product_image_url: "https://picsum.photos/seed/echeveria/400/400", quantity: 1, unit_price: 3500, subtotal: 3500 },
    ],
    created_at: "2026-03-08T09:00:00Z",
    updated_at: "2026-03-08T09:00:00Z",
  },
];
